name: Daily Album Sharing

on:
  workflow_run:
    workflows: ["Daily Album Automation"]
    types:
      - completed

jobs:
  share:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    env:
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
      SPOTIFY_PLAYLIST_ID: ${{ secrets.SPOTIFY_PLAYLIST_ID }}
      SITE_URL: ${{ vars.SITE_URL }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm ci
      - name: Set current date
        id: date
        run: |
          echo "date=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Run share script
        run: node scripts/share.js data/album-of-the-day/${{ steps.date.outputs.date }}.json
